dist: trusty
language: python
python:
  - "3.6"
install:
  - pip install -e .
  - pip install pytest-cov
addons:
  sonarcloud:
    organization: "jiejyun-liu"
    token:
      secure: $SONAR_TOKEN
script:
  - pytest --cov travis_ci_pytest tests/
  - sonar-scanner
